version: "3.4"

services:

  app:
    build:
      context: .
      dockerfile: DockerfileDebug
    ports:
      - "8080:5100"
      - "8081:5101"
      - "44447:44447"
      - "4567:4567"
    depends_on:
      - db
    volumes:
      - ./src:/app
  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    
    environment:
      SA_PASSWORD: "${BD_PASSWORD}"
      ACCEPT_EULA: "Y"